### DISCUSSION TITLE
v5 Vmess 如何设置 alterId ？

### DISCUSSION THREAD

**Discussion by MoraxMa** [v2fly/v2ray-core#2181] [Q&A]
原 v4 配置：
"clients": [
    {
        "id": "DC13312B-7BA7-C1FF-8761-1F452D72F725",
        "alterId": 0
    }
]

现在 v5 配置
"users": [
    "DC13312B-7BA7-C1FF-8761-1F452D72F725"
]

之前的alterId应该配置在哪里？

**Comment by AkinoKaede** [comment]
It's removed.

**Reply by MoraxMa** [reply]
但是clash中还是必须配置alterId

**Reply by SakuraSakuraSakuraChan** [reply]
Clash不用变

**Reply by MoraxMa** [reply]
但是会报错:用户认证错误;
我是这样配置的
```json
"inbounds": [
    {
        "protocol": "vmess",
        "settings": {
            "users": [
                "DC13312B-7BA7-C1FF-8761-1F452D72F725"
            ]
        },
        "port": 8080,
        "listen": "0.0.0.0",
        "tag": "in-vmess",
        "sniffing": {},
        "streamSettings": {
            "transport": "ws",
            "transportSettings": {
                "acceptProxyProtocol": false,
                "path": "/v2ray"
            },
            "security": "none",
            "securitySettings": {}
        }
    }
]
```

clash 的配置是这样的
```yaml
proxies:
- name: vmess-ws
  type: vmess
  server: 
  port: 443
  cipher: auto
  uuid: DC13312B-7BA7-C1FF-8761-1F452D72F725
  alterId: 0
  network: ws
  udp: true
  tls: true
  ws-opts:
    path: /v2ray
    headers:
      Host: 
```

我是用nginx代理的，所以v2fly没有配置security
