### DISCUSSION TITLE
配置如下，貌似端口，ip，域名都没问题，却连不上服务器，其他类似配置却能连上

### DISCUSSION THREAD

**Discussion by fredericky123** [v2fly/v2ray-core#2306] [General]
vmess1 2 3 能正常连，唯有4连不上服务器
而1说明域名没问题，2用的cf workers反代，说明自选ip没问题，3说明ipv6连接没问题，唯独4的配置连不上服务器(与2同一个自选ip)，同一网络，同时测试，why?

```
# VMess
- name: "vmess1"
  type: vmess
  server: us.pp.ua
  port: 443
  uuid: 19b51791-8017-403d-9914-xxxxxxxx
  alterId: 0
  cipher: auto
  # udp: true
  tls: true
  # skip-cert-verify: true
  servername: us.pp.ua # priority over wss host
  network: ws
  ws-opts:
    path: /oqwbvws
    headers:
      Host: us.pp.ua
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol

  # VMess
- name: "vmess2"
  type: vmess
  server: 172.64.xxx.72
  port: 443
  uuid: 19b51791-8017-403d-9914-xxxxxxxx
  alterId: 0
  cipher: auto
  # udp: true
  tls: true
  # skip-cert-verify: true
  servername: uscfworker.xxx.tk # priority over wss host
  network: ws
  ws-opts:
    path: /oqwbvws
    headers:
      Host: uscfworker.xxx.tk
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol

# VMess
- name: "vmess3"
  type: vmess
  server: "2606:xxxxx:25f:ce8xxxxxxx5"
  port: 443
  uuid: 19b51791-8017-403d-9914-xxxxxxxx
  alterId: 0
  cipher: auto
  # udp: true
  tls: true
  # skip-cert-verify: true
  servername: us.pp.ua # priority over wss host
  network: ws
  ws-opts:
    path: /oqwbvws
    headers:
      Host: us.pp.ua
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol

  # VMess
- name: "vmess4"
  type: vmess
  server: 172.64.xxx.72
  port: 443
  uuid: 19b51791-8017-403d-9914-xxxxxxxx
  alterId: 0
  cipher: auto
  # udp: true
  tls: true
  # skip-cert-verify: true
  servername: us.pp.ua # priority over wss host
  network: ws
  ws-opts:
    path: /oqwbvws
    headers:
      Host: us.pp.ua
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
```
