### DISCUSSION TITLE
v2fly v5 trojan+ws 服务器配置模板

### DISCUSSION THREAD

**Discussion by aaro-n** [v2fly/v2ray-core#2315] [Q&A]
## 问题
我正在使用` v2fly v4 + vless + ws +caddy v1  `想要将服务端升级为` v2fly v5 + trojan + ws +caddy v1  `，目前已经可以通过docker compose 运行容器，但我不会配置trojan的服务端，尝试查询文档及搜索v2fly v5 trojan 模板，无法解决问题。
## 配置文件
`docker-compose.yml `
```
version: "3"
services:
  v2ray:
    image: v2fly/v2fly-core:latest
    container_name: v2ray-5
    restart: always
    command: run -c  /etc/v2fly/config.json
    ports:
      - "127.0.0.1:51222:10090"
    volumes:
      - ./log:/var/log/v2fly/
      - ./config.json:/etc/v2fly/config.json:ro
```
`Caddyfile  caddy v1`
```
fq.123456.xyz:930 {
 gzip
 log /tmp/翻墙.log
 tls xxxx@gmail.com
 proxy / https://www.baidu.com
 proxy /fd3ad3c7-9705-4b9a-83fd-99ecf89c0cfe localhost:51222 {
    websocket
    header_upstream -Origin
   }
}
```
`config.json`
```
{
    "log":{
    "access": "/var/log/v2fly/access.log",
    "error": "/var/log/v2fly/error.log",
    "level": "info"
       },

    "inbounds": [
        {
            "port": 10090,
            "protocol": "trojan",
            "settings": {
                "users": [
                    {
                        "password": "83wz5Jtkf4ErN725vFGc",
                        "email": "xxxx@gmail.com"
                    }
                ]
            }
          },

        "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "acceptProxyProtocol": true, 
          "path": "/fd3ad3c7-9705-4b9a-83fd-99ecf89c0cfe" 
         }
        },

      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
    
    ],
    "outbounds": [
        {
            "protocol": "freedom"
        }
    ]
}
```
v2fly 运行上述配置文件后提示
```
Attaching to v2ray-5
v2ray-5  | V2Ray 5.2.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)
v2ray-5  | A unified platform for anti-censorship.
v2ray-5  | Failed to start: main/commands: failed to load config: [/etc/v2fly/config.json] > infra/conf/serial: failed to read config file at line 22 char 25 > invalid character ':' after array element
v2ray-5 exited with code 0
```
