### ISSUE TITLE
Failed to read config file

### ISSUE THREAD

**Issue by NoverNobida** [v2fly/v2ray-core#1915]
## 你正在使用哪个版本的 V2Ray？

docker v2fly/v2fly-core:v4.45.2

## 你的使用场景是什么？

部署阶段

## 你看到的异常现象是什么？

相同的配置文件，完全使用官方给出的[配置文件](https://guide.v2fly.org/advanced/wss_and_web.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE)，在`v2ray/official:latest`测试配置文件`v2ray --test`成功，并运行正常，但是在`v2fly/v2fly-core:v4.45.2`测试不成功

## 你期待看到的正常表现是怎样的？

正常读取配置文件

## 请附上你的配置

**服务端配置：**

```json
#官方示例配置
{
  "inbounds": [
    {
      "port": 10000,
      "listen":"127.0.0.1",//只监听 127.0.0.1，避免除本机外的机器探测到开放了 10000 端口
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "b831381d-6324-4d53-ad4f-8cda48b30811",
            "alterId": 0
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/ray"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}
```

**客户端配置：**

```javascript
none
```

## 请附上出错时软件输出的错误日志

**服务器端错误日志：**

**客户端错误日志：**

```
none
```

## 请附上访问日志

```
none
```

## 其它相关的配置文件（如 Nginx）和相关日志

`docker-compose.yml`

```yml
version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core:v4.45.2
    container_name: v2ray
    environment:
      - TZ=Asia/Shanghai
    restart: always
    command: v2ray --test -config=/etc/v2ray/config.json
    volumes:
      - ./data:/etc/v2ray
      - ./logs:/var/log/v2ray
    ports:
      - "10000:10000"
 ```

## 如果 V2Ray 无法启动，请附上 `--test` 命令的输出

```
Attaching to v2ray
v2ray    | V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
v2ray    | A unified platform for anti-censorship.
v2ray    | 2022/08/19 09:46:27 Using config from STDIN
v2ray    | panic: infra/conf/serial: failed to read config file > EOF
v2ray    | 
v2ray    | goroutine 1 [running]:
v2ray    | github.com/v2fly/v2ray-core/v4/common.Must(...)
v2ray    |      github.com/v2fly/v2ray-core/v4/common/common.go:27
v2ray    | github.com/v2fly/v2ray-core/v4/main/jsonem.init.0.func1({0xcb3600?, 0xc00000df80?})
v2ray    |      github.com/v2fly/v2ray-core/v4/main/jsonem/jsonem.go:27 +0x32e
v2ray    | github.com/v2fly/v2ray-core/v4.LoadConfig({0xe0b26e, 0x4}, {0xe0d28f?, 0x0?}, {0xcb3600, 0xc00000df80})
v2ray    |      github.com/v2fly/v2ray-core/v4/config.go:73 +0x1da
v2ray    | main.startV2Ray()
v2ray    |      github.com/v2fly/v2ray-core/v4/main/main.go:109 +0xed
v2ray    | main.main()
v2ray    |      github.com/v2fly/v2ray-core/v4/main/main.go:138 +0x9f

```
