### ISSUE TITLE
Reverse proxy does not works with trojan protocal (使用trojan协议时无法使用反向代理)

### ISSUE THREAD

**Issue by zq1997** [v2fly/v2ray-core#2250]
## What version of V2Ray are you using?

V2Ray 5.2.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.19.4 linux/amd64)

## What's your scenario of using V2Ray?

Reverse Proxy

## What problems have you encountered?

It does not work with `trojan` protocal, while it works with `vless` protocal.

## What's your expectation?

`trojan` can be used as the protocal for the tunnel.

## Please attach your configuration here

**Server(portal) configuration:**

```yaml
log:
  access: /var/log/v2ray/access.log
  loglevel: debug
reverse:
  portals:
  - domain: aaa.private.test
    tag: aaa-portal
inbounds:
- protocol: vless
  port: 10000
  tag: tunnel-vless
  settings:
    decryption: none
    clients:
    - email: tunnel
      id: 6ba03c02-8fc8-11ed-88c2-1fb064fe3abd
  streamSettings:
    network: ws
    wsSettings:
      path: /my-path
- protocol: trojan
  port: 10001
  tag: tunnel-trojan
  settings:
    clients:
    - email: tunnel
      password: my-password
  streamSettings:
    network: ws
    wsSettings:
      path: /my-path
- protocol: dokodemo-door
  port: 10002
  tag: aaa-ssh
  settings:
    address: 127.0.0.1
    network: tcp
    port: 22
outbounds:
- protocol: freedom
  settings:
    domainStrategy: UseIPv4
  tag: free
routing:
  domainStrategy: AsIs
  rules:
  - type: field
    inboundTag:
    - aaa-ssh
    outboundTag: aaa-portal
  - type: field
    domain:
    - full:aaa.private.test
    outboundTag: aaa-portal
```

**Client(bridge) configuration:**

```yaml
log:
  access: none
  loglevel: debug
outbounds:
- protocol: vless
  settings:
    vnext:
    - address: # address here
      port: 10000
      users:
      - id: 6ba03c02-8fc8-11ed-88c2-1fb064fe3abd
        encryption: none
  streamSettings:
    network: ws
    wsSettings:
      path: /my-path
  tag: tunnel-vless
- protocol: trojan
  settings:
    servers:
    - address: # address here
      password: my-password
      port: 10001
  streamSettings:
    network: ws
    wsSettings:
      path: /my-path
  tag: tunnel-trojan
- protocol: freedom
  tag: local-out
reverse:
  bridges:
  - domain: aaa.private.test
    tag: bridge
routing:
  domainStrategy: AsIs
  rules:
  - type: field
    inboundTag:
    - bridge
    domain:
    - full:aaa.private.test
    outboundTag: tunnel-trojan # it works if we change it to tunnel-vless
  - type: field
    inboundTag:
    - bridge
    outboundTag: local-out
```
