### ISSUE TITLE
v5配置域名分流无法生效

### ISSUE THREAD

**Issue by dev-techmoe** [v2fly/v2ray-core#2493]
版本5.2.1，关键配置文件（yaml）：
```yaml
outbounds:
  - tag: wireproxy
    protocol: socks
    settings:
      servers:
        - address: 127.0.0.1
          port: 20808

router:
  domainStrategy: AsIs
  rule:
    - tag: wireproxy
      domain:
        - type: Plain
          value: ifconfig.co
```
如此配置，访问ifconfig.co依然还是走的默认的freedom，日志里看到此域名也依然是freedom。

**Comment by dev-techmoe** [comment]
v5文档有问题，遵循v4版本文档后正常。

希望文档准确性能提高一些。

**Comment by mydogshitgold** [comment]
What is your log? 

Do you have `destOveride` enabled? Without `sniffing` and `destOveride` it's possible for clients to resolve domains using OS specified DNS servers and thus send proxy requests by IP instead of domain names.

How are your routing rules organized? Rules take precedence by virtue of their position. Your domain rules will be ignored if the request matches a rule before it.

**Comment by dev-techmoe** [comment]
> What is your log?
> 
> Do you have `destOveride` enabled? Without `sniffing` and `destOveride` it's possible for clients to resolve domains using OS specified DNS servers and thus send proxy requests by IP instead of domain names.
> 
> How are your routing rules organized? Rules take precedence by virtue of their position. Your domain rules will be ignored if the request matches a rule before it.

hey @mydogshitgold , thank you for your reply!

I have resolved the issue. However, please be aware that the documentation for version 5 ([link](https://www.v2fly.org/en_US/v5/config/router.html)) is not accurate for the current version.

Here is my current configuration, which works for me. I have written it based on the v4 documentation.

```yaml
outbounds:
  - tag: wireproxy
    protocol: socks
    settings:
      servers:
        - address: 127.0.0.1
          port: 20808

routing:
  domainStrategy: AsIs
  rules:
    - type: field
      outboundTag: wireproxy
      domain: 
       - domain:ip.gs
```

I will continue to monitor this issue and reopen this issue if necessary.
